### ISSUE TITLE
maggiore 5

### ISSUE THREAD

**Issue by FabioZTessitore** [MarioDomenicoDM/helloworld_c#1]
non va bene, che succede se i numeri sono tutti negativi?

**Comment by MarioDomenicoDM** [comment]
![funziona](https://cloud.githubusercontent.com/assets/24526830/22617125/300fc830-eabd-11e6-9f49-719a67dd41ad.jpg)


Funziona ;)

**Comment by FabioZTessitore** [comment]
appena puoi carica la versione giusta
